datasets:
  raw:
    housing:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/raw/datasets/housing/housing.csv
      driver_params: {}
  
  cleaned:
    housing:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/cleaned/cleaned.csv
      driver_params: {}

  cleaned_house:
    housing_cleaned:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/cleaned/house_cleaned.csv
      driver_params: {}

  processed:
    train_x:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/processed/train_x.csv
      driver_params: {}

    train_y:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/processed/train_y.csv
      driver_params: {}

    test_x:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/processed/test_x.csv
      driver_params: {}

    test_y:
      type: ds
      format: csv
      uri: /home/anitha512/mle-training/data/processed/test_y.csv
      driver_params: {}



